#!/usr/bin/env python3
"""Tests for install_dev.py CI mode behavior.

This test suite validates that install_dev.py properly skips dependency
recompilation when running in CI environment (CI=true).

Test Strategy:
- Test A: Normal mode (no CI env) -> pip-compile should run
- Test B: CI mode (CI=true) -> pip-compile should be skipped
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest


@pytest.fixture
def mock_workspace(tmp_path: Path) -> Path:
    """Create a mock workspace with required structure."""
    # Create requirements directory
    req_dir = tmp_path / "requirements"
    req_dir.mkdir()

    # Create dev.in file
    dev_in = req_dir / "dev.in"
    dev_in.write_text("pytest>=7.0.0\nruff>=0.1.0\n")

    # Create dev.txt file
    dev_txt = req_dir / "dev.txt"
    dev_txt.write_text(
        "# This file is autogenerated by pip-compile\npytest==7.4.0\nruff==0.1.6\n",
    )

    return tmp_path


class TestInstallDevCIMode:
    """Test suite for CI mode detection in install_dev.py."""

    @patch("scripts.cli.install_dev.safe_pip_compile")
    @patch("subprocess.run")
    @patch("sys.executable", "/usr/bin/python3")
    @patch.dict("os.environ", {}, clear=True)
    def test_normal_mode_runs_pip_compile(
        self,
        mock_subprocess_run: MagicMock,
        mock_safe_pip_compile: MagicMock,
        mock_workspace: Path,
    ) -> None:
        """Test that pip-compile runs in normal mode (no CI env var).

        Expected behavior:
        - CI environment variable is NOT set
        - pip-compile should be invoked
        - Dependencies are recompiled
        """
        # Arrange
        from scripts.cli.install_dev import install_dev_environment

        # Mock successful subprocess calls
        mock_subprocess_run.return_value = subprocess.CompletedProcess(
            args=[],
            returncode=0,
            stdout="Success",
            stderr="",
        )

        # Mock safe_pip_compile
        mock_safe_pip_compile.return_value = subprocess.CompletedProcess(
            args=["pip-compile"],
            returncode=0,
            stdout="Compiled successfully",
            stderr="",
        )

        # Act
        with patch("shutil.which", return_value="/usr/bin/pip-compile"):
            result = install_dev_environment(mock_workspace)

        # Assert
        assert result == 0, "Installation should succeed"

        # Verify safe_pip_compile was called (which wraps pip-compile)
        assert mock_safe_pip_compile.call_count == 1, (
            "safe_pip_compile should be invoked once in normal mode. "
            f"Actual calls: {mock_safe_pip_compile.call_count}"
        )

    @patch("subprocess.run")
    @patch("sys.executable", "/usr/bin/python3")
    @patch.dict("os.environ", {"CI": "true"}, clear=True)
    def test_ci_mode_skips_pip_compile(
        self,
        mock_subprocess_run: MagicMock,
        mock_workspace: Path,
    ) -> None:
        """Test that pip-compile is skipped in CI mode (CI=true).

        Expected behavior:
        - CI environment variable IS set
        - pip-compile should NOT be invoked
        - Only pip install commands run
        """
        # Arrange
        from scripts.cli.install_dev import install_dev_environment

        # Mock successful subprocess calls
        mock_subprocess_run.return_value = subprocess.CompletedProcess(
            args=[],
            returncode=0,
            stdout="Success",
            stderr="",
        )

        # Act
        result = install_dev_environment(mock_workspace)

        # Assert
        assert result == 0, "Installation should succeed in CI mode"

        # Verify pip-compile was NOT called
        pip_compile_calls = [
            call
            for call in mock_subprocess_run.call_args_list
            if any(
                "pip-compile" in str(arg) or "piptools" in str(arg)
                for arg in call[0][0]
            )
        ]

        assert len(pip_compile_calls) == 0, (
            "pip-compile should be SKIPPED in CI mode. "
            f"Found calls: {pip_compile_calls}"
        )

        # Verify pip install was still called (for editable install and pinned deps)
        pip_install_calls = [
            call
            for call in mock_subprocess_run.call_args_list
            if "pip" in str(call[0][0]) and "install" in str(call[0][0])
        ]

        assert len(pip_install_calls) >= 2, (
            "Expected at least 2 pip install calls: "
            "1) pip install -e .[dev], 2) pip install -r requirements/dev.txt"
        )

    @patch("subprocess.run")
    @patch("sys.executable", "/usr/bin/python3")
    @patch.dict("os.environ", {"CI": "1"}, clear=True)
    def test_ci_mode_various_values(
        self,
        mock_subprocess_run: MagicMock,
        mock_workspace: Path,
    ) -> None:
        """Test that CI mode works with various truthy values.

        Expected behavior:
        - CI=1, CI=True, CI=yes all trigger CI mode
        - pip-compile is skipped for all cases
        """
        # Arrange
        from scripts.cli.install_dev import install_dev_environment

        # Mock successful subprocess calls
        mock_subprocess_run.return_value = subprocess.CompletedProcess(
            args=[],
            returncode=0,
            stdout="Success",
            stderr="",
        )

        # Act
        result = install_dev_environment(mock_workspace)

        # Assert
        assert result == 0, "Installation should succeed"

        # Verify pip-compile was NOT called
        pip_compile_calls = [
            call
            for call in mock_subprocess_run.call_args_list
            if any(
                "pip-compile" in str(arg) or "piptools" in str(arg)
                for arg in call[0][0]
            )
        ]

        assert len(pip_compile_calls) == 0, "pip-compile should be skipped with CI=1"
