"""Configurações e constantes para Mock CI Integration.

Este módulo centraliza todas as configurações hardcoded do sistema de
integração CI/CD, incluindo detecção de ambientes, classificação de
severidade e templates de mensagens.
"""

from pathlib import Path
from typing import Final

# ============================================================
# Detecção de Ambiente CI/CD
# ============================================================

CI_ENVIRONMENT_VARS: Final[dict[str, str]] = {
    "GITHUB_ACTIONS": "github-actions",
    "GITLAB_CI": "gitlab-ci",
    "JENKINS_URL": "jenkins",
    "TRAVIS": "travis-ci",
    "CIRCLECI": "circle-ci",
    "AZURE_DEVOPS": "azure-devops",
    "CI": "generic-ci",
}
"""Mapeamento de variáveis de ambiente para nomes de CI/CD.

A detecção é feita na ordem do dicionário. O primeiro match determina
o ambiente. Se nenhum match, retorna 'local'.
"""

# ============================================================
# Classificação de Prioridade e Bloqueio
# ============================================================

BLOCKING_MOCK_TYPES: Final[set[str]] = {"HTTP_REQUEST", "SUBPROCESS"}
"""Tipos de mock considerados bloqueadores.

Testes com esses tipos de mock sem tratamento adequado podem causar
falhas imprevisíveis em ambientes CI/CD (timeouts, chamadas externas, etc).
"""

HIGH_SEVERITY_THRESHOLD: Final[int] = 3
"""Número máximo de issues de alta prioridade antes de WARNING."""

BLOCKING_THRESHOLD: Final[int] = 1
"""Número mínimo de issues bloqueadores para FAILURE."""

# ============================================================
# Templates de Mensagens
# ============================================================

COMMIT_MESSAGE_TEMPLATE: Final[str] = """feat(tests): Auto-fix test mocks via CI/CD

- Applied {mock_fixes} mock fixes
- Fixed {validation_fixes} validation issues
- Generated by: CI Test Mock Integration

[skip ci]
"""
"""Template para mensagens de commit automáticos.

Formato: Conventional Commits (feat/fix/chore)
Inclui [skip ci] para evitar loops infinitos em pipelines.

Placeholders:
    {mock_fixes}: Número de correções de mock aplicadas
    {validation_fixes}: Número de correções de validação aplicadas
"""

# ============================================================
# Configurações de Relatórios
# ============================================================

REPORT_FILENAME_TEMPLATE: Final[str] = "ci_test_mock_report_{timestamp}.json"
"""Template para nome de arquivo de relatório.

Placeholder:
    {timestamp}: Formato YYYYMMDD_HHMMSS (UTC)
"""

REPORT_INDENT: Final[int] = 2
"""Indentação para arquivos JSON de relatório."""

# ============================================================
# Configurações de Logging
# ============================================================

LOG_FORMAT: Final[str] = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
"""Formato de log para ambientes CI/CD."""

LOG_DATE_FORMAT: Final[str] = "%Y-%m-%d %H:%M:%S"
"""Formato de data para logs."""

# ============================================================
# Paths e Arquivos
# ============================================================


def get_config_file(script_dir: Path) -> Path:
    """Resolve o caminho do arquivo de configuração do gerador de mocks.

    Args:
        script_dir: Diretório do script CLI (scripts/cli/)

    Returns:
        Path para test_mock_config.yaml

    Raises:
        FileNotFoundError: Se o arquivo não existir

    Example:
        >>> from pathlib import Path
        >>> script_dir = Path("/project/scripts/cli")
        >>> config = get_config_file(script_dir)
        >>> print(config)
        /project/scripts/cli/test_mock_config.yaml

    """
    config_file = script_dir / "test_mock_config.yaml"

    if not config_file.exists():
        msg = f"Config do gerador não encontrado: {config_file}"
        raise FileNotFoundError(msg)

    return config_file


def get_report_filename(workspace_root: Path, timestamp: str) -> Path:
    """Gera o caminho completo para um arquivo de relatório.

    Args:
        workspace_root: Diretório raiz do workspace
        timestamp: Timestamp no formato YYYYMMDD_HHMMSS

    Returns:
        Path completo para o arquivo de relatório

    Example:
        >>> from pathlib import Path
        >>> workspace = Path("/project")
        >>> filename = get_report_filename(workspace, "20250601_143052")
        >>> print(filename.name)
        ci_test_mock_report_20250601_143052.json

    """
    filename = REPORT_FILENAME_TEMPLATE.format(timestamp=timestamp)
    return workspace_root / filename


# ============================================================
# Configurações de Status
# ============================================================


def determine_status(
    validation_results: dict[str, bool],
    critical_count: int,
    blocking_count: int,
) -> str:
    """Determina o status geral baseado em resultados de verificação.

    Args:
        validation_results: Dicionário de validações (nome -> passou?)
        critical_count: Número de issues críticos (severity=HIGH)
        blocking_count: Número de issues bloqueadores

    Returns:
        Status como string: "SUCCESS", "WARNING", ou "FAILURE"

    Logic:
        - FAILURE: se validações falharam OU há issues bloqueadores
        - WARNING: se há issues críticos acima do threshold
        - SUCCESS: caso contrário

    Example:
        >>> results = {"has_tests": True, "has_mocks": True}
        >>> status = determine_status(results, critical_count=2, blocking_count=0)
        >>> print(status)
        SUCCESS

    """
    # Falha se validações básicas falharam
    if not all(validation_results.values()):
        return "FAILURE"

    # Falha se há problemas bloqueadores
    if blocking_count >= BLOCKING_THRESHOLD:
        return "FAILURE"

    # Warning se há problemas críticos
    if critical_count >= HIGH_SEVERITY_THRESHOLD:
        return "WARNING"

    return "SUCCESS"


# ============================================================
# Utilitários de Formatação
# ============================================================


def format_commit_message(mock_fixes: int, validation_fixes: int) -> str:
    """Formata a mensagem de commit usando o template.

    Args:
        mock_fixes: Número de correções de mock aplicadas
        validation_fixes: Número de correções de validação

    Returns:
        Mensagem de commit formatada

    Example:
        >>> msg = format_commit_message(mock_fixes=5, validation_fixes=2)
        >>> print("Applied 5 mock fixes" in msg)
        True

    """
    return COMMIT_MESSAGE_TEMPLATE.format(
        mock_fixes=mock_fixes,
        validation_fixes=validation_fixes,
    )
